name: Generate Index Page

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - 'generate_index.py'
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install markdown

      - name: Generate index.html from README
        run: python3 generate_index.py

      - name: Commit index.html if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "🔄 Auto-regenerated index.html"
          git push
