name: Generate index.html from README

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - 'createrepo.py'

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate index.html
        run: python3 createrepo.py

      - name: Commit and push index.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update index.html from README" || echo "No changes to commit"
          git push
