name: Generate Index Page

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - README.md
      - generate_index.py

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for switching branches later

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Generate index.html
        run: |
          python generate_index.py
          mkdir -p /tmp/output
          cp index.html /tmp/output/index.html

      - name: Switch to gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch gh-pages || git checkout --orphan gh-pages
          git reset --hard
          rm -f index.html
          cp /tmp/output/index.html ./index.html
          git add index.html
          git commit -m "📄 Update generated index page" || echo "No changes to commit"
          git push origin gh-pages --force
